#pragma once
enum SHADER { SHADER_VERTEX, SHADER_FRAGMENT, SHADER_END };
enum OBJECT {OBJECT_PLAYER, OBJECT_COLLIDER, OBJECT_LIGHT, OBJECT_TERRAIN,OBJECT_BULLET ,OBJECT_PLANT, OBJECT_MONSTER, OBJECT_FLAG,OBJECT_CAMERA, OBJECT_LEFTWHEEL, OBJECT_RIGHTWHEEL, OBJECT_CANNON, OBJECT_FOOD, OBJECT_END};
enum STATE { STATE_RIGHT, STATE_UP, STATE_LOOK, STATE_POSITION, STATE_END };

enum MOUSEBUTTON { DIM_LBUTTON, DIM_RBUTTON, DIM_WHEEL, DIM_XBUTTON };
enum MOUSEMOVE { DIM_X, DIM_Y, DIM_Z };

enum CAMERA {CAMERA_DEBUG, CAMERA_QUARTAR, CAMERA_PLAYER, CAMERA_END};